### ISSUE TITLE
what php version?

### ISSUE THREAD

**Issue by mttindustries** [jamesl1001/deviantART-API#1]
I tried it and it just doesn't work, even using your rss urls from the demo absolutely nothing shows up. What php version are you using? I'm on 7.2.10

**Comment by jamesl1001** [comment]
I was running 5.6.* and after changing it to 7.1.14 some errors appeared on the demo site:
`Warning: getDeviations(): Node no longer exists in deviantArt-API/getDeviations.php on line 24`

I have fixed these errors in fdf3a9ec5a62d8e18904856ffadcda2d1602ef70.

Perhaps this was your issue? Try pulling the latest commit and see if that solves it for you.

If not, please provide some code to reproduce the issue for me to debug.

**Comment by jamesl1001** [comment]
Closing - no response.
Please feel free to let me know if you have any further issues.
