### ISSUE TITLE
More than 60 items?

### ISSUE THREAD

**Issue by OnlyAlec** [jamesl1001/deviantART-API#2]
Apparently the function only returns 60 rss items. Is there a way to get more items?

**Comment by jamesl1001** [comment]
Good spot! I haven't got the time to update this repo atm, however I did come across a potential solution for you.

It looks like the RSS feed's limit is 60, but it supports pagination.

When I open the [example RSS feed](https://backend.deviantart.com/rss.xml?q=gallery:fu51on/27123391), I can see the following line:

`<atom:link rel="next" href="https://backend.deviantart.com/rss.xml?type=deviation&q=gallery%3Afu51on%2F27123391&offset=60"/>`

If you update `getDeviations()` to extract that tag, you should be able to build a loop to extract more than 60 items. Looks like it only appears when there are more pages.

Also, please feel free to submit a PR if you want to build the pagination into this script, I'll happily review it!
