### ISSUE TITLE
Filtering mature content

### ISSUE THREAD

**Issue by serioucsat** [jamesl1001/deviantART-API#3]
Do you know if it's possible to add the mature content filter? When using this, the results show all deviations including the mature ones, and adding `&mature_content=false` (as indicated in [DeviantArt's API documentation](https://www.deviantart.com/developers/http/v1/20210526/object/deviation)) to the url does nothing,

**Comment by jamesl1001** [comment]
Hi @serioucsat,

It seems like you are correct. The `mature_content` parameter is only for `GET` or `POST` requests made via the API, so it won't work for the RSS feeds.

If you want to use the RSS feeds over the API, one workaround I thought of could be to use the `<media:rating>` value in the response to identify if the content is labelled as `adult`.

However, there are a few things to bear in mind with this approach:
1. It's unclear whether this value is equivalent to the "Mature Content" checkbox set by the poster, and could therefore be abused.
2. It's unclear whether DeviantArt can override this value if they deem it necessary.
3. It's unclear whether filtering by `<media:rating>` and setting `mature_content` would return the exact same results.

I hope that helps!
