### ISSUE TITLE
Unclear instruction in gallery nr

### ISSUE THREAD

**Issue by Ry3yr** [jamesl1001/deviantART-API#4]
In the example
https://backend.deviantart.com/rss.xml?q=gallery:fu51on/27123391

The number 27123391 appears as "gallery" ?

It is not clear where this number (always) stems from ?
•Featured
•Scraps 
seem to relay no number et all ?
What number applies to it ?
Do I even need a number for it ?

F.e. user @swanamii:
https://www.deviantart.com/swanamii/gallery/16690/ocs 
Has a /number/ inb4 ocs ..

But that doesnt apply to all galleries

- Ry3yR

**Comment by Ry3yr** [comment]
I felt like creating a querystring version and make all links target_blank:

```
<a target="_blank" href="?artist=swanamii&galleryid=16690" style=color:blue>Gallery</a><br><br>


<link rel="stylesheet" type="text/css" href="styles.css" />
<div class="deviations">
<?php
    require_once('getDeviations.php');
    $artist = $_GET['artist'];
    $galleryid = $_GET['galleryid'];
    $deviations = getDeviations("https://backend.deviantart.com/rss.xml?q=gallery:{$artist}/{$galleryid}");
    foreach($deviations as $key => $deviation): ?>
        <div class="deviation">
            <div class="col col-p">
                <a target=_blank href="<?= $deviations[$key]->url; ?>"><h2><?= $deviations[$key]->title; ?></h2></a>
                <img src="<?= $deviations[$key]->image; ?>" alt="<?= $deviations[$key]->title; ?>" class="deviation_image"/>
                <p>Thumbnail src: <a target=_blank href="<?= $deviations[$key]->thumbS; ?>">150px</a> | <a target=_blank href="<?= $deviations[$key]->thumbL; ?>">300px</a>
            </div>
            <div class="col col-s">
                <h2>Deviation Info</h2>
                <p><small><?= $deviations[$key]->date; ?></small></p>
                <p><strong><?= $deviations[$key]->desc; ?></strong></p>
                <p>Rating: <?= $deviations[$key]->rating; ?></p>
                <p>Category: <a target=_blank href="http://browse.deviantart.com/<?= $deviations[$key]->categoryUrl; ?>"><?= $deviations[$key]->category; ?></a></p>
                <p>By <a target=_blank href="<?= $deviations[$key]->deviantUrl; ?>"><?= $deviations[$key]->deviantName; ?></a></p>
                <img src="<?= $deviations[$key]->deviantAvatar; ?>"/>
                <p><?= $deviations[$key]->copyright; ?></p>
            </div>
        </div>
<?php endforeach; ?>
```

**Comment by jamesl1001** [comment]
Hi there,

I've worked out how to get the data from the "Featured" gallery!

To find the ID for your "Featured" gallery:
1. Navigate to: https://www.deviantart.com/swanamii/gallery
2. Hover over the "Featured" link under "Gallery"
3. You can see the ID in the URL (https://www.deviantart.com/swanamii/gallery/16656/featured)

https://backend.deviantart.com/rss.xml?q=gallery:swanamii/16656

You can also see this ID using the Network tab in your browser's devtools. When you switch gallery, there's a request to `https://frog.wix.com/da-client` which contains the `itemid` in its parameters.

In the Network tab I can see `itemid=-2` for Scraps, but neither `https://backend.deviantart.com/rss.xml?q=gallery:swanamii/-2` nor `https://backend.deviantart.com/rss.xml?q=gallery:swanamii/%2D2` work.

If you figure out a way to get Scraps working, please do let me know.

**Comment by Ry3yr** [comment]
Excellent 😺 !

Here is a lil php to find the featured gallery for any user desired:

```
    <form method="POST" action="">
        <input type="text" name="username" placeholder="Enter username" required>
        <button type="submit">Search</button>
    </form>
    <div id="result">
        <?php
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $username = $_POST['username'];
            $url = "https://www.deviantart.com/{$username}/gallery/";
            $content = file_get_contents($url);
            $pattern = '/<a href="https:\/\/www.deviantart.com\/' . preg_quote($username) . '\/gallery\/(\d+)\/featured">/';
            preg_match($pattern, $content, $matches);
            if (isset($matches[1])) {
                $galleryId = $matches[1];
                echo "Featured gallery URL: <a href=\"https://www.deviantart.com/{$username}/gallery/{$galleryId}/featured\">https://www.deviantart.com/{$username}/gallery/{$galleryId}/featured</a>";
            } else {
                echo "Featured gallery not found.";
            }
        }
        ?>
    </div>
</body>
</html>

```
Gotta look into Scraps.


EDIT: Not all featured galleries work ?

BackendResponse is ok,
https://backend.deviantart.com/rss.xml?q=gallery:aoikurayami1/84802465

But
https://alcea-wisteria.de/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/fetchpub.php?artist=aoikurayami1&galleryid=84802465
Produces

> [20-Feb-2024 14:58:12 UTC] PHP Fatal error:  Uncaught Error: Call to a member function attributes() on null in /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/getDeviations.php:24
> Stack trace:
> #0 /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/fetchpub.php(9): getDeviations()
> #1 {main}
>   thrown in /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/getDeviations.php on line 24

I think your parser takes issue with this gallery 😹 ?

Addendum:
Is it possible the "-2" you see in devtools is actually the pagenumber on that scraps page ?

Maybe the "Scraps" Folder is not exposed in the backend?:

`"Scraps are not officially part of the gallery it seems, or at least they don't get listed as part of said "All" folder. There is also no special "Scraps" folder as part of the folders list provided by the OAuth API, which is why the Scraps extractor has to do its own "thing" and, together with individual Deviations, is the only reason you need cookies in the first place. `"https://github.com/mikf/gallery-dl/issues/531
https://github.com/mikf/gallery-dl/issues/5258

**Comment by jamesl1001** [comment]
> I think your parser takes issue with this gallery

https://backend.deviantart.com/rss.xml?q=gallery:aoikurayami1/84802465

In the response, there's one `item` which doesn't follow the same format as the rest of the items:

```
<item>
  <title>DA Upload</title>
  <link>https://www.deviantart.com/aoikurayami1/art/DA-Upload-976722669</link>
  <guid isPermaLink="true">https://www.deviantart.com/aoikurayami1/art/DA-Upload-976722669</guid>
  <pubDate>Sat, 12 Aug 2023 02:02:51 PDT</pubDate>
  <media:title type="plain">DA Upload</media:title>
  <media:keywords/>
  <media:rating>nonadult</media:rating>
  <media:category label="Applications">apps</media:category>
  <media:credit role="author" scheme="urn:ebu">aoikurayami1</media:credit>
  <media:credit role="author" scheme="urn:ebu">https://a.deviantart.net/avatars/a/o/aoikurayami1.jpg?4</media:credit>
  <media:copyright url="https://www.deviantart.com/aoikurayami1">Copyright 2023-2024 aoikurayami1</media:copyright>
  <media:description type="html">JS Uploader</media:description>
</item>
```

Perhaps adding null coalescing operators to https://github.com/jamesl1001/deviantART-API/blob/master/getDeviations.php#L20-L33 would solve this error?

e.g. `"thumbS" => $item->children('media', true)->thumbnail[0]->attributes()->url ?? null,`

If you have time to test it, please do open a pull request!

---

> Is it possible the "-2" you see in devtools is actually the pagenumber on that scraps page ?

I don't think so. Even when I navigate to page 3, `itemid` is still `-2`.

**Comment by Ry3yr** [comment]
I tried your suggested change.

Result:
[11-Apr-2024 10:58:13 UTC] PHP Fatal error:  Uncaught Error: Call to a member function attributes() on null in /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/getDeviations.php:24
Stack trace:
#0 /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/fetch.php(16): getDeviations()
#1 {main}
  thrown in /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/getDeviations.php on line 24
[11-Apr-2024 10:58:29 UTC] PHP Fatal error:  Uncaught Error: Call to a member function attributes() on null in /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/getDeviations.php:24
Stack trace:
#0 /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/fetch.php(16): getDeviations()
#1 {main}
  thrown in /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/getDeviations.php on line 24


![Screenshot_20240411-125921_FX](https://github.com/jamesl1001/deviantART-API/assets/17431197/1a9fa172-1e4d-48b6-b853-7fcc58508983)
